### ISSUE TITLE
Installation in linux machine

### ISSUE THREAD

**Issue by DDGmichigan** [jayponder/Tinker#1]
Hi,
I have downloaded the latest version of TINKER ( Tinker Complete Distribution (ZIP, 44.5 Mb))
Following instructions of Christoph J. given in the configure folder, I did these steps
1. copy  configure.ac  and  Makefile.am to the source folder
2. cd ../source
3. autoreconf -i -v
4. ./configure
5 make

The steps seem okay till ./configure

However when I type make, I get the following error. please help

[source]$ make
/bin/sh ./libtool  --tag=F77   --mode=compile gfortran  -g -O2 -c -o action.lo action.f
libtool: compile:  gfortran -g -O2 -c action.f  -fPIC -o .libs/action.o
libtool: compile:  gfortran -g -O2 -c action.f -o action.o >/dev/null 2>&1
/bin/sh ./libtool  --tag=F77   --mode=compile gfortran  -g -O2 -c -o active.lo active.f
libtool: compile:  gfortran -g -O2 -c active.f  -fPIC -o .libs/active.o
active.f:20.9:

      use atoms
         1
Fatal Error: Can't open module file 'atoms.mod' for reading at (1): No such file or directory
make: *** [active.lo] Error 1

**Comment by jayponder** [comment]
Don't try to use "configure" scripts. Just use the Makefile in the /make directory.

You should examine the Makefile, and change the directory locations at the top of file to match where you are building and installing, and uncomment the correct block of environment variables for your operating system and compiler combination. Then copy the Makefile into the /source directory and type "make".

Note that before using the Tinker Makefile, you will first need to have available the FFTW Fourier transform static libraries. You can build these libraries from the code provided in the /fftw directory, following the instructions in the 0README file.
