### ISSUE TITLE
isokinetic integrator question

### ISSUE THREAD

**Issue by swails** [jayponder/tinker#22]
This is mainly a question for @dmargul (apologies for doing it here -- I don't know your email address).

I'm trying to get a version of the SINR integrator implemented in OpenMM (for use with both fixed-charge and AMOEBA force fields).  What I _expected_ to see in the code based on what I remember from the talk at Telluride and conversations with various people was to see the short-range forces comprised of the basic bonded terms in addition to short-range VDW and electrostatic forces, and then the long-range stuff had the long-range forces and the reciprocal sum of the multipole (or charge) interactions.  Unless I'm reading the code incorrectly, though, what appears to be happening is that [all vdW and electrostatic interactions are being turned off](https://github.com/jayponder/tinker/blob/isokinetic/source/stoch_respa2.f#L550-L576) even the SR stuff (which is turned off with the "slow-evolving" forces).

Can you clue me into the basic components of the force at the inner (and outer) timesteps in the SINR integrator here?

Thanks!

**Comment by dmargul** [comment]
(I will add my e-mail address to the readme on the isokinetic branch.)

There are several time step levels. In practice, you will likely only need three but I have written it for four. 

In the "grad1" subroutine you linked, only the fastest forces are calculated -- the bonded interactions. 

"grad2" covers torsions (although you can include them in the same time step as "grad1" if your multiplier n_bond = 1)

"grad3" is used for short-range vdW and electrostatics. https://github.com/jayponder/tinker/blob/isokinetic/source/stoch_respa2.f#L838-L856

"grad4" is the longest time step, which is for long-range vdW and electrostatics. 
https://github.com/jayponder/tinker/blob/isokinetic/source/stoch_respa2.f#L979-L1001

**Comment by dmargul** [comment]
I think I see what really caused this confusion --- my bad.  

The comments in the code about what forces are being turned on/off are leftover from their parent code: the gradslow/gradfast subroutines in respa.f, which was a two-time step scheme.  I should clean that up.

**Comment by swails** [comment]
Ah, I was misreading those and putting too much stock in the comments (as you mentioned :smiley:).  OK, I'll have to rework how I'm doing that, then.  Another quick question if you have the time (it would save me a bit of code hunting):

What *exactly* is in the short-range electrostatic energy?  Is it *just* a dipole-converged direct-space multipole calculation with the same erfc switching function that's used in the full PME calculation (but without any reciprocal space contribution)?  I presume the long-range calculations (for both vdW and electrostatic) is all interactions *outside* the short-range cutoff (but inside the LR cutoff), and for electrostatics also the reciprocal space calc?

What I *think* I need to do with OpenMM is the following:

1. For short-range nonbonded, turn off the reciprocal space calc in the multipole force, keep the same long-range multipole force PME parameters, and set the cutoff short (how short?)
2. For the long-range nonbonded, subtract out the short-range nonbonded forces (since there's no way to exclude them in the nonbond loop inside OpenMM currently), and keep the reciprocal part of PME on, then multiply by nrespa.

Is this more or less correct?

**Comment by swails** [comment]
Looking at the code for `empoleSR`, there is no call to `emrecip1`, but there *is* a call to a short-range variant of the induced dipole iterator (preconditioned conjugate gradient, it appears) where all of the long-range stuff is omitted there.  I think this answers my question.  If I'm wrong (and it doesn't make sense to me that I would be), and the PME switching function is *not* used for the short-range part of the calculation, please let me know.
