### ISSUE TITLE
dynamic_omm compatibility with release OpenMM

### ISSUE THREAD

**Issue by rtb1c13** [jayponder/tinker#24]
Hi everyone,

For reference for anyone trying to use dynamic_omm, the current dev version here only seems to work with the dev version of OpenMM being worked on in the Ren group (https://github.com/pren/openmm-amoeba), not the latest OpenMM release. There are extra stretch-torsion potential terms, vdW softcore developments etc.

I think this is fairly well known ( @swails mentioned the issue here https://github.com/pandegroup/openmm/issues/1439) but thought an issue would be useful to keep track of developments here too, at least for me. I recognise it's a work in progress!

Note that the current 7.1.3 Tinker release still works ok - it's the changes in 7.2 that break compatibility with OpenMM 6.3 or 7.0 for me.
Thanks,
Richard

**Comment by jayponder** [comment]
Our goal is for the current TINKER version available in this repo to work correctly with the version of OpenMM in the Pengyu Ren TINKER-OpenMM repo mentioned above. The interface routines can be found in openmm/* in this repo.
