### ISSUE TITLE
dynamic_omm compile error

### ISSUE THREAD

**Issue by ever4cyth** [jayponder/tinker#25]
downloaded tinker package from github today, openmm is the latest version 7.0. Could anyone please help?

make all
gfortran -c -O3 -ffast-math -fopenmp angbnd.f -o angbnd.o 
gfortran -c -O3 -ffast-math -fopenmp angpot.f -o angpot.o 
gfortran -c -O3 -ffast-math -fopenmp angtor.f -o angtor.o 
gfortran -c -O3 -ffast-math -fopenmp sizes.f -o sizes.o 
gfortran -c -O3 -ffast-math -fopenmp atomid.f -o atomid.o 
gfortran -c -O3 -ffast-math -fopenmp atoms.f -o atoms.o 
gfortran -c -O3 -ffast-math -fopenmp bath.f -o bath.o 
gfortran -c -O3 -ffast-math -fopenmp bitor.f -o bitor.o 
gfortran -c -O3 -ffast-math -fopenmp bndpot.f -o bndpot.o 
gfortran -c -O3 -ffast-math -fopenmp bndstr.f -o bndstr.o 
gfortran -c -O3 -ffast-math -fopenmp bound.f -o bound.o 
gfortran -c -O3 -ffast-math -fopenmp boxes.f -o boxes.o 
gfortran -c -O3 -ffast-math -fopenmp chgpot.f -o chgpot.o 
gfortran -c -O3 -ffast-math -fopenmp couple.f -o couple.o 
gfortran -c -O3 -ffast-math -fopenmp deriv.f -o deriv.o 
gfortran -c -O3 -ffast-math -fopenmp energi.f -o energi.o 
gfortran -c -O3 -ffast-math -fopenmp ewald.f -o ewald.o 
gfortran -c -O3 -ffast-math -fopenmp freeze.f -o freeze.o 
gfortran -c -O3 -ffast-math -fopenmp group.f -o group.o 
gfortran -c -O3 -ffast-math -fopenmp inform.f -o inform.o 
gfortran -c -O3 -ffast-math -fopenmp iounit.f -o iounit.o 
gfortran -c -O3 -ffast-math -fopenmp keys.f -o keys.o 
gfortran -c -O3 -ffast-math -fopenmp ktrtor.f -o ktrtor.o 
gfortran -c -O3 -ffast-math -fopenmp kvdws.f -o kvdws.o 
gfortran -c -O3 -ffast-math -fopenmp limits.f -o limits.o 
gfortran -c -O3 -ffast-math -fopenmp mdstuf.f -o mdstuf.o 
gfortran -c -O3 -ffast-math -fopenmp moldyn.f -o moldyn.o 
gfortran -c -O3 -ffast-math -fopenmp mplpot.f -o mplpot.o 
gfortran -c -O3 -ffast-math -fopenmp mpole.f -o mpole.o 
gfortran -c -O3 -ffast-math -fopenmp mutant.f -o mutant.o 
gfortran -c -O3 -ffast-math -fopenmp nonpol.f -o nonpol.o 
gfortran -c -O3 -ffast-math -fopenmp opbend.f -o opbend.o 
gfortran -c -O3 -ffast-math -fopenmp openmm.f -o openmm.o 
gfortran -c -O3 -ffast-math -fopenmp openmp.f -o openmp.o 
gfortran -c -O3 -ffast-math -fopenmp pitors.f -o pitors.o 
gfortran -c -O3 -ffast-math -fopenmp pme.f -o pme.o 
gfortran -c -O3 -ffast-math -fopenmp polar.f -o polar.o 
gfortran -c -O3 -ffast-math -fopenmp polgrp.f -o polgrp.o 
gfortran -c -O3 -ffast-math -fopenmp polpot.f -o polpot.o 
gfortran -c -O3 -ffast-math -fopenmp potent.f -o potent.o 
gfortran -c -O3 -ffast-math -fopenmp restrn.f -o restrn.o 
gfortran -c -O3 -ffast-math -fopenmp solute.f -o solute.o 
gfortran -c -O3 -ffast-math -fopenmp stodyn.f -o stodyn.o 
gfortran -c -O3 -ffast-math -fopenmp strbnd.f -o strbnd.o 
gfortran -c -O3 -ffast-math -fopenmp strtor.f -o strtor.o 
gfortran -c -O3 -ffast-math -fopenmp torpot.f -o torpot.o 
gfortran -c -O3 -ffast-math -fopenmp tors.f -o tors.o 
gfortran -c -O3 -ffast-math -fopenmp tortor.f -o tortor.o 
gfortran -c -O3 -ffast-math -fopenmp units.f -o units.o 
gfortran -c -O3 -ffast-math -fopenmp urey.f -o urey.o 
gfortran -c -O3 -ffast-math -fopenmp urypot.f -o urypot.o 
gfortran -c -O3 -ffast-math -fopenmp usage.f -o usage.o 
gfortran -c -O3 -ffast-math -fopenmp vdw.f -o vdw.o 
gfortran -c -O3 -ffast-math -fopenmp vdwpot.f -o vdwpot.o 
gfortran -c -O3 -ffast-math -fopenmp dynamic_omm.f -o dynamic_omm.o 
g++ -c -O3 -ffast-math -fopenmp -I/home/magno/protein/openmm/include ommstuff.cpp
ommstuff.cpp:85:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> angbnd__’ with linkage [enabled by default]
 } angbnd__;
   ^
ommstuff.cpp:107:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> angpot__’ with linkage [enabled by default]
 } angpot__;
   ^
ommstuff.cpp:123:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> atomid__’ with linkage [enabled by default]
 } atomid__;
   ^
ommstuff.cpp:131:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> atoms__’ with linkage [enabled by default]
 } atoms__;
   ^
ommstuff.cpp:156:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> bath__’ with linkage [enabled by default]
 } bath__;
   ^
ommstuff.cpp:161:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> bitor__’ with linkage [enabled by default]
 } bitor__;
   ^
ommstuff.cpp:168:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> bndpot__’ with linkage [enabled by default]
 } bndpot__;
   ^
ommstuff.cpp:175:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> bndstr__’ with linkage [enabled by default]
 } bndstr__;
   ^
ommstuff.cpp:183:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> bound__’ with linkage [enabled by default]
 } bound__;
   ^
ommstuff.cpp:210:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> boxes__’ with linkage [enabled by default]
 } boxes__;
   ^
ommstuff.cpp:222:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> chgpot__’ with linkage [enabled by default]
 } chgpot__;
   ^
ommstuff.cpp:233:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> couple__’ with linkage [enabled by default]
 } couple__;
   ^
ommstuff.cpp:262:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> deriv__’ with linkage [enabled by default]
 } deriv__;
   ^
ommstuff.cpp:291:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> energi__’ with linkage [enabled by default]
 } energi__;
   ^
ommstuff.cpp:296:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> ewald__’ with linkage [enabled by default]
 } ewald__;
   ^
ommstuff.cpp:308:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> freeze__’ with linkage [enabled by default]
 } freeze__;
   ^
ommstuff.cpp:320:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> group__’ with linkage [enabled by default]
 } group__;
   ^
ommstuff.cpp:332:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> inform__’ with linkage [enabled by default]
 } inform__;
   ^
ommstuff.cpp:347:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> ktrtor__’ with linkage [enabled by default]
 } ktrtor__;
   ^
ommstuff.cpp:354:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> kvdwpr__’ with linkage [enabled by default]
 } kvdwpr__;
   ^
ommstuff.cpp:362:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> kvdws__’ with linkage [enabled by default]
 } kvdws__;
   ^
ommstuff.cpp:382:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> limits__’ with linkage [enabled by default]
 } limits__; 
   ^
ommstuff.cpp:393:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> mdstuf__’ with linkage [enabled by default]
 } mdstuf__;
   ^
ommstuff.cpp:399:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> moldyn__’ with linkage [enabled by default]
 } moldyn__;
   ^
ommstuff.cpp:406:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> mplpot__’ with linkage [enabled by default]
 } mplpot__;
   ^
ommstuff.cpp:420:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> mpole__’ with linkage [enabled by default]
 } mpole__;
   ^
ommstuff.cpp:435:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> mutant__’ with linkage [enabled by default]
 } mutant__;
   ^
ommstuff.cpp:453:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> nonpol__’ with linkage [enabled by default]
 } nonpol__;
   ^
ommstuff.cpp:459:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> opbend__’ with linkage [enabled by default]
 } opbend__;
   ^
ommstuff.cpp:465:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> pitors__’ with linkage [enabled by default]
 } pitors__;
   ^
ommstuff.cpp:482:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> pme__’ with linkage [enabled by default]
 } pme__;
   ^
ommstuff.cpp:506:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> polar__’ with linkage [enabled by default]
 } polar__;
   ^
ommstuff.cpp:521:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> polgrp__’ with linkage [enabled by default]
 } polgrp__;
   ^
ommstuff.cpp:541:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> polpot__’ with linkage [enabled by default]
 } polpot__;
   ^
ommstuff.cpp:571:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> potent__’ with linkage [enabled by default]
 } potent__;
   ^
ommstuff.cpp:601:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> restrn__’ with linkage [enabled by default]
 } restrn__;
   ^
ommstuff.cpp:612:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> sizes__’ with linkage [enabled by default]
 } sizes__;
   ^
ommstuff.cpp:638:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> solute__’ with linkage [enabled by default]
 } solute__;
   ^
ommstuff.cpp:644:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> stodyn__’ with linkage [enabled by default]
 } stodyn__;
   ^
ommstuff.cpp:650:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> strbnd__’ with linkage [enabled by default]
 } strbnd__;
   ^
ommstuff.cpp:666:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> torpot__’ with linkage [enabled by default]
 } torpot__;
   ^
ommstuff.cpp:677:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> tors__’ with linkage [enabled by default]
 } tors__;
   ^
ommstuff.cpp:682:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> tortor__’ with linkage [enabled by default]
 } tortor__;
   ^
ommstuff.cpp:700:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> units__’ with linkage [enabled by default]
 } units__;
   ^
ommstuff.cpp:707:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> urey__’ with linkage [enabled by default]
 } urey__;
   ^
ommstuff.cpp:713:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> urypot__’ with linkage [enabled by default]
 } urypot__;
   ^
ommstuff.cpp:719:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> usage__’ with linkage [enabled by default]
 } usage__;
   ^
ommstuff.cpp:733:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> vdw__’ with linkage [enabled by default]
 } vdw__;
   ^
ommstuff.cpp:756:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> vdwpot__’ with linkage [enabled by default]
 } vdwpot__;
   ^
ommstuff.cpp: In function ‘void setupAmoebaStretchTorsionForce(OpenMM_System*, FILE*)’:
ommstuff.cpp:2192:4: error: ‘OpenMM_AmoebaStretchTorsionForce’ was not declared in this scope
    OpenMM_AmoebaStretchTorsionForce* amoebaStretchTorsionForce;
    ^
ommstuff.cpp:2192:38: error: ‘amoebaStretchTorsionForce’ was not declared in this scope
    OpenMM_AmoebaStretchTorsionForce* amoebaStretchTorsionForce;
                                      ^
ommstuff.cpp:2193:73: error: ‘OpenMM_AmoebaStretchTorsionForce_create’ was not declared in this scope
    amoebaStretchTorsionForce = OpenMM_AmoebaStretchTorsionForce_create ();
                                                                         ^
ommstuff.cpp:2246:75: error: ‘OpenMM_AmoebaStretchTorsionForce_addStretchTorsion’ was not declared in this scope
                           torpot__.storunit * (*(strtor__.kst + 9*ii + 8)));
                                                                           ^
ommstuff.cpp: In function ‘void setupAmoebaAngleTorsionForce(OpenMM_System*, FILE*)’:
ommstuff.cpp:2257:4: error: ‘OpenMM_AmoebaAngleTorsionForce’ was not declared in this scope
    OpenMM_AmoebaAngleTorsionForce* amoebaAngleTorsionForce;
    ^
ommstuff.cpp:2257:36: error: ‘amoebaAngleTorsionForce’ was not declared in this scope
    OpenMM_AmoebaAngleTorsionForce* amoebaAngleTorsionForce;
                                    ^
ommstuff.cpp:2258:69: error: ‘OpenMM_AmoebaAngleTorsionForce_create’ was not declared in this scope
    amoebaAngleTorsionForce = OpenMM_AmoebaAngleTorsionForce_create ();
                                                                     ^
ommstuff.cpp:2297:60: error: ‘OpenMM_AmoebaAngleTorsionForce_addAngleTorsion’ was not declared in this scope
                           * (*(angtor__.kant + 6 * ii + 5)));
                                                            ^
ommstuff.cpp: In function ‘void setupAmoebaVdwForce(OpenMM_System*, FILE*)’:
ommstuff.cpp:2503:63: error: too many arguments to function ‘int OpenMM_AmoebaVdwForce_addParticle(OpenMM_AmoebaVdwForce*, int, double, double, double)’
                               vdw__.kred[ii], mutant__.vlambda);
                                                               ^
In file included from ommstuff.cpp:57:0:
/home/magno/protein/openmm/include/AmoebaOpenMMCWrapper.h:59:33: note: declared here
 extern OPENMM_EXPORT_AMOEBA int OpenMM_AmoebaVdwForce_addParticle(OpenMM_AmoebaVdwForce* target, int parentIndex, double sigma, double epsilon, double reductionFactor);
                                 ^
ommstuff.cpp:2509:50: error: too many arguments to function ‘int OpenMM_AmoebaVdwForce_addParticle(OpenMM_AmoebaVdwForce*, int, double, double, double)’
                               vdw__.kred[ii], 1.0);
                                                  ^
In file included from ommstuff.cpp:57:0:
/home/magno/protein/openmm/include/AmoebaOpenMMCWrapper.h:59:33: note: declared here
 extern OPENMM_EXPORT_AMOEBA int OpenMM_AmoebaVdwForce_addParticle(OpenMM_AmoebaVdwForce* target, int parentIndex, double sigma, double epsilon, double reductionFactor);
                                 ^
ommstuff.cpp:2557:69: error: ‘OpenMM_AmoebaVdwForce_computeCombinedSigmaEpsilon’ was not declared in this scope
    OpenMM_AmoebaVdwForce_computeCombinedSigmaEpsilon (amoebaVdwForce);
                                                                     ^
ommstuff.cpp:2590:57: error: ‘OpenMM_AmoebaVdwForce_addVdwprByOldTypes’ was not declared in this scope
                         combinedEpsilon*OpenMM_KJPerKcal);
                                                         ^
ommstuff.cpp: In function ‘void openmm_init_(void**, double*)’:
ommstuff.cpp:3388:70: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘void*’ [-Wformat=]
       (void) fprintf (log, "\n OpenMMDataHandle:  %x\n", (void*)(omm));
                                                                      ^
ommstuff.cpp:3389:76: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘void*’ [-Wformat=]
       (void) fprintf (log, "\n Integrator:  %x\n", (void*)(omm->integrator));
                                                                            ^
ommstuff.cpp: In function ‘void openmm_validate_(int*)’:
ommstuff.cpp:3934:22: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    char* ixnString = "Interaction Not Currently Supported by OpenMM.\n";
                      ^
ommstuff.cpp: In function ‘int openmm_test_()’:
ommstuff.cpp:4363:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaPotentialsTest";
                ^
ommstuff.cpp:4394:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaHarmonicBondTest";
                ^
ommstuff.cpp:4405:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaHarmonicAngleTest";
                ^
ommstuff.cpp:4413:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaStretchBendTest";
                ^
ommstuff.cpp:4421:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaUreyBradleyForceTest";
                ^
ommstuff.cpp:4428:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaOutOfPlaneBendTest";
                ^
ommstuff.cpp:4435:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaTorsionTest";
                ^
ommstuff.cpp:4442:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaPiTorsionTest";
                ^
ommstuff.cpp:4449:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaStretchTorsionTest";
                ^
ommstuff.cpp:4456:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaAngleTorsionTest";
                ^
ommstuff.cpp:4463:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaTorsionTorsionTest";
                ^
ommstuff.cpp:4471:19: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
          testName = "AmoebaVdwTest";
                   ^
ommstuff.cpp:4473:19: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
          testName = "AmoebaVdwNoCutoffTest";
                   ^
ommstuff.cpp:4485:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaRestraintTest";
                ^
ommstuff.cpp:4507:19: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
          testName = "AmoebaMultipoleDirectTest";
                   ^
ommstuff.cpp:4509:19: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
          testName = "AmoebaMultipoleMutualTest";
                   ^
ommstuff.cpp:4521:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
       testName = "AmoebaWcaDispersionTest";
                ^
ommstuff.cpp:4569:19: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
          testName = "AmoebaKirkwoodDirectTest";
                   ^
ommstuff.cpp:4571:19: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
          testName = "AmoebaKirkwoodMutualTest";
                   ^
make: *** [ommstuff.o] Error 1

**Comment by swails** [comment]
You can't use the OpenMM release code or the version at http://github.com/pandegroup/openmm with this version of Tinker.  I believe the OpenMM version you need to use is here: https://github.com/pren/tinker-openmm

Alternatively, you can roll back the Tinker code to revision 2568b124efd3f16c27b5a1fc55186865db8c7653 and go from there.  Unfortunately, there have been a few important bug fixes to OpenMM that haven't yet been merged into the tinker-openmm fork, so *I* would roll Tinker back to the version that works with the standard OpenMM release.

**Comment by pren** [comment]
http://biomol.bme.utexas.edu/tinker-openmm/index.php/Main_Page

Thanks,
Pengyu
________________________________

**Comment by ever4cyth** [comment]
Thanks Swails and Pren for your quick response.

I had problems even compiling tinker-openmm from github site. Too many errors like
tinker-openmm-master/plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp:47:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

tinker-openmm-master/plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp:2683:13: error: ‘array’ is not a member of ‘std’
             std::array<int, 2> tp;
tinker-openmm-master/plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp:2683:24: error: expected primary-expression before ‘int’
             std::array<int, 2> tp;
tinker-openmm-master/plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp:2683:24: error: expected ‘;’ before ‘int’
tinker-openmm-master/plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp:2684:13: error: ‘tp’ was not declared in this scope
             tp[0] = i;

tinker-openmm github site doesn't have issue option so I can't ask question there.

**Comment by rtb1c13** [comment]
Hi,

I had the same problem when using gnu compilers on ubuntu (4.8.4 in my case). As the message suggests, it's fixable by passing the option '-std=c++11' to the compiler. Set CMAKE_CXX_FLAGS=-std=c++11 (in addition to anything you already have there) and it should remove this error.

Presumably the intel compilers use 2011 C++ standards by default so this error doesn't pop up there, though I haven't tried.

Thanks,
Richard

**Comment by ever4cyth** [comment]
Thanks, Richard! tinker-openmm is compiled successfully with your tip.

Now I faced problem compiling tinker downloaded from github, as suggested from Pengyu.
....
a - zcoord.o
ranlib -c libtinker.a
ranlib: invalid option -- 'c'
gfortran -O3 -ffast-math -fopenmp -static-libgcc -L/home/magno/protein/tinker/fftw/lib -L/home/magno/protein/openmmtk/lib -o dynamic_omm.x dynamic_omm.o ommstuff.o libtinker.a -lstdc++ -L. -lfftw3_threads -lfftw3 -lfftw3_threads -lfftw3 -lOpenMM -lOpenMMAmoeba
libtinker.a(initial.o): In function `initial_':
initial.f:(.text+0x6d): undefined reference to `kmp_set_stacksize_s_'
initial.f:(.text+0x79): undefined reference to `kmp_set_blocktime_'
collect2: error: ld returned 1 exit status
make: *** [dynamic_omm.x] Error 1

**Comment by swails** [comment]
If you are not using the Intel compilers, you need to comment-out the `kmp_*` calls in initial.F90

**Comment by ever4cyth** [comment]
Thanks again, Swails! it works now.
