### ISSUE TITLE
Poledit 'priority' function

### ISSUE THREAD

**Issue by rtb1c13** [jayponder/tinker#29]
Hi Jay,

Within the poledit 'priority' function, (line 1034 onwards), the loop for assigning the priority of bonded atoms is slightly different for atom `ia` and atom `ib`. In my view, lines 1076-1079 should read:

```
if (m .ge. kb1) then
   kb2 = kb1
   kb1 = m
else if (m .gt. kb2) then
```

similarly to lines 1062-1065 for atom `ia` / atomic no. `ka2`. This causes problems with automatic frame assignment in very rare cases, so just wanted to check this wasn't deliberate for any reason before submitting a pull request. I can provide an example case if needed. Thanks go to Asmit of Teresa Head-Gordon's group for pointing this out.
Thanks,
Richard

**Comment by jayponder** [comment]
Hi Richard,

Sorry for not getting to this sooner. It does indeed appear to be a bug. I've fixed it on GitHub and in the TINKER 8.1.1 release.

Thanks, Jay
